export const categories = [
  {uuid: "105", name: "2D E-drawing"},
  {uuid: "27", name: "3dModeling"},
  {uuid: "25", name: "3dPrinting"},
  {uuid: "72", name: "Amateur Radio"},
  {uuid: "95", name: "Arduino"},
  {uuid: "71", name: "Automotive"},
  {uuid: "69", name: "Blacksmithing"},
  {uuid: "101", name: "Board of Directors"},
  {uuid: "104", name: "CAD"},
  {uuid: "20", name: "Ceramics"},
  {uuid: "85", name: "Committee Meetings"},
  {uuid: "87", name: "Costuming"},
  {uuid: "83", name: "Digital Media"},
  {uuid: "84", name: "DMS Business Meetings"},
  {uuid: "13", name: "Drawing/Painting"},
  {uuid: "61", name: "Drones/RC Planes"},
  {uuid: "8", name: "Dye Sublimation"},
  {uuid: "98", name: "Education"},
  {uuid: "67", name: "Electronics/Microcontrollers"},
  {uuid: "79", name: "Engraving"},
  {uuid: "94", name: "Expansion"},
  {uuid: "3", name: "Fiber Arts"},
  {uuid: "77", name: "Finance"},
  {uuid: "82", name: "Glass Working"},
  {uuid: "65", name: "Graphic Design Software "},
  {uuid: "92", name: "Hatchers Armory"},
  {uuid: "74", name: "Information Technology"},
  {uuid: "103", name: "Infrastructure Group"},
  {uuid: "70", name: "Jewelry "},
  {uuid: "88", name: "Lapidary"},
  {uuid: "45", name: "Laser"},
  {uuid: "4", name: "Leatherworking"},
  {uuid: "76", name: "Logistics"},
  {uuid: "38", name: "Machining"},
  {uuid: "93", name: "Marketing"},
  {uuid: "100", name: "Member Services"},
  {uuid: "66", name: "Metalworking"},
  {uuid: "6", name: "Mold Making"},
  {uuid: "89", name: "Motorsports"},
  {uuid: "29", name: "Photography/Videography/Audiography"},
  {uuid: "102", name: "Plastics (P-IG)"},
  {uuid: "81", name: "Printmaking"},
  {uuid: "68", name: "Programming/Software Development"},
  {uuid: "90", name: "Public Relations"},
  {uuid: "96", name: "Raspberry Pi"},
  {uuid: "31", name: "Reloading"},
  {uuid: "97", name: "Resin"},
  {uuid: "17", name: "Robotics"},
  {uuid: "73", name: "Science"},
  {uuid: "11", name: "Sculpting"},
  {uuid: "75", name: "Sewing"},
  {uuid: "10", name: "Silk Screening"},
  {uuid: "86", name: "Small Metals"},
  {uuid: "80", name: "Training Development SIG"},
  {uuid: "47", name: "VECTOR"},
  {uuid: "78", name: "Vintage Computers"},
  {uuid: "7", name: "Vinyl Cutting"},
  {uuid: "99", name: "Volunteer Opportunities"},
  {uuid: "32", name: "Welding"},
  {uuid: "91", name: "Wood Turning"},
  {uuid: "63", name: "Woodworking"},
]
export const tools = [
  {uuid: "84", name: "001 - No Tool Reservation Required"},
  {uuid: "42", name: "3D Printer"},
  {uuid: "11", name: "3D Scanner"},
  {uuid: "56", name: "3D Vacuum Former"},
  {uuid: "32", name: "Automotive Lift"},
  {uuid: "34", name: "Bridgeport Mill"},
  {uuid: "38", name: "Clay Slab Roller"},
  {uuid: "35", name: "Colchester Metal Lathe"},
  {uuid: "57", name: "CrashCart TV and PC"},
  {uuid: "70", name: "Creative Arts Silhouette Cameo 2"},
  {uuid: "8", name: "Digital Camera"},
  {uuid: "45", name: "Dye Sublimation/Heat Press"},
  {uuid: "44", name: "Electronics Workbench tools"},
  {uuid: "3", name: "Embroidery Machine"},
  {uuid: "49", name: "Fiber Tools"},
  {uuid: "33", name: "HAAS VF2 CNC Mill"},
  {uuid: "55", name: "Induction Forge"},
  {uuid: "62", name: "Industrial Leather Sewing Machine"},
  {uuid: "40", name: "Jewelry Casting Equipment"},
  {uuid: "60", name: "Jewelry Hand Tools"},
  {uuid: "58", name: "Jewelry HydroFlux"},
  {uuid: "59", name: "Jewelry Rolling Mill"},
  {uuid: "83", name: "Jewelry Wax Resin Printer"},
  {uuid: "5", name: "Large Format Photo Printer"},
  {uuid: "47", name: "Large Woodshop Tools"},
  {uuid: "80", name: "Laser - Epilog Fusion"},
  {uuid: "71", name: "Laser - Epilog Zing"},
  {uuid: "43", name: "Laser - Thunder"},
  {uuid: "2", name: "Leather Sewing Machine"},
  {uuid: "82", name: "Machine Shop Shapeoko 3 XXL"},
  {uuid: "68", name: "Metal Shop Bench Grinders"},
  {uuid: "27", name: "Metal Shop CNC Plasma Cutter"},
  {uuid: "64", name: "Metal Shop Flux Core Welder"},
  {uuid: "65", name: "Metal Shop Heat Treating Kiln"},
  {uuid: "69", name: "Metal Shop Large Buffer"},
  {uuid: "66", name: "Metal Shop Large Oven"},
  {uuid: "28", name: "Metal Shop Media Blaster"},
  {uuid: "67", name: "Metal Shop Sheet Metal Forming Tools"},
  {uuid: "63", name: "Metal Shop Tubing Bender"},
  {uuid: "52", name: "Metaza Engraver"},
  {uuid: "61", name: "Microwave Oven - GlassWorks"},
  {uuid: "24", name: "MIG welder"},
  {uuid: "20", name: "Multicam CNC Router"},
  {uuid: "46", name: "National Instruments Virtual Bench"},
  {uuid: "36", name: "Pottery Wheels"},
  {uuid: "23", name: "Power Hand Tools"},
  {uuid: "85", name: "Printmaking - Letterpress"},
  {uuid: "77", name: "Resin Pressure Pot"},
  {uuid: "78", name: "Resin Vacuum Chamber"},
  {uuid: "48", name: "Serger"},
  {uuid: "1", name: "Sewing Machine"},
  {uuid: "50", name: "Shapeoko2"},
  {uuid: "54", name: "Sherline Lathe"},
  {uuid: "53", name: "Sherline Mill"},
  {uuid: "26", name: "Stick Welder"},
  {uuid: "81", name: "Streaming Cart"},
  {uuid: "25", name: "TIG Welder"},
  {uuid: "4", name: "Vinyl Cutter"},
  {uuid: "51", name: "Woodshop Lathes"},
]
export const rooms = [{uuid: "8", name: "Classroom - Interactive"},
  {uuid: "9", name: "Classroom - Lecture Hall"},
  {uuid: "28", name: "Classroom - North Lobby"},
  {uuid: "57", name: "Classroom - Pillar of Solitude"},
  {uuid: "11", name: "Classroom - Purple"},
  {uuid: "33", name: "Classroom - Wet"},
  {uuid: "39", name: "Common Area - Common Room"},
  {uuid: "2", name: "Common Area - Back Parking Lot"},
  {uuid: "24", name: "Common Area - Galley"},
  {uuid: "36", name: "Common Area - North Flex Area"},
  {uuid: "38", name: "Common Area - North Lobby"},
  {uuid: "27", name: "Common Area - South Lobby"},
  {uuid: "37", name: "Conference Room - North Lobby"},
  {uuid: "56", name: "Lab - Digital Media"},
  {uuid: "45", name: "Lab - Electronics"},
  {uuid: "53", name: "Lab - Science - Biology"},
  {uuid: "46", name: "Lab - Science - Chemistry"},
  {uuid: "16", name: "Laser - Thunder"},
  {uuid: "23", name: "Offsite (See Event Description)"},
  {uuid: "58", name: "Online Only"},
  {uuid: "5", name: "Studio - Creative Arts "},
  {uuid: "55", name: "Studio - Creative Arts - Digital Arts"},
  {uuid: "52", name: "Studio - Creative Arts - Island"},
  {uuid: "54", name: "Studio - Creative Arts - Sewing"},
  {uuid: "1", name: "Workshop - 3D Fabrication"},
  {uuid: "31", name: "Workshop - Auto Lift Bay"},
  {uuid: "14", name: "Workshop - Auto South Bay"},
  {uuid: "62", name: "Workshop - Blacksmithing"},
  {uuid: "25", name: "Workshop - Ceramics"},
  {uuid: "15", name: "Workshop - Foundry"},
  {uuid: "48", name: "Workshop - GlassWorks"},
  {uuid: "26", name: "Workshop - Jewelry / Small Metals"},
  {uuid: "59", name: "Workshop - Laser - Epilog Fusion"},
  {uuid: "30", name: "Workshop - Laser - Epilog Zing"},
  {uuid: "17", name: "Workshop - Machine Shop"},
  {uuid: "10", name: "Workshop - Metalworking"},
  {uuid: "21", name: "Workshop - Open Table Area Central"},
  {uuid: "20", name: "Workshop - Open Table Area North (Woodworking Only)"},
  {uuid: "22", name: "Workshop - Open Table Area South"},
  {uuid: "49", name: "Workshop - Printmaking"},
  {uuid: "47", name: "Workshop - VECTOR"},
  {uuid: "12", name: "Workshop - Woodworking (Excludes Lathe and Multicam)"},
  {uuid: "29", name: "Workshop - Woodworking - Lathes (Excludes Multicam and Woodworking)"},
  {uuid: "61", name: "Workshop - Woodworking - Multicam (Excludes Lathes and Woodworking)"},
  {uuid: "13", name: "Workshop(Historical) Do Not Use"},
]

let datas = {
  categories,
  tools,
  rooms
};
export default datas;